name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019 # newer versions will not find older .net assembly references

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out source
        uses: actions/checkout@v2
      # Restores project dependencies that are necessary for building it
      - name: Restore dependencies
        run: dotnet restore
      - name: Get repository name
        id: get_repo
        run: |
          $repo = $(Split-Path ${{ github.repository }} -Leaf)
          echo "::set-output name=name::$repo"
          echo "Repository name is $repo"
      # Gets the project version from the .csproj
      - name: Get project version
        id: get_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: "src/${{ steps.get_repo.outputs.name }}.csproj"
      # Parses version from obtained version 
      - name: Parse project version
        id: version
        uses: release-kit/semver@v1.0.10
        with:
          input: ${{ steps.get_version.outputs.version }}
      # Sets the project version in the .csproj
      - name: Set project version
        uses: vers-one/dotnet-project-version-updater@v1.0
        with:
          file: "src/${{ steps.get_repo.outputs.name }}.csproj"
          version: "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ github.run_number }}"
      # Builds the project using the specified arguments
      - name: Build with msbuild
        run: dotnet build --configuration Release
      # Packs the project into a nuget package
      - name: Pack for nuget
        run: dotnet pack --configuration Release --no-restore
      # Publish nuget package
      - name: Publish to nuget
        run: dotnet nuget push src/bin/Release/*.nupkg --source ${{ secrets.MYGET_SOURCE }} --api-key ${{ secrets.MYGET_KEY }} --skip-duplicate
      # Uploads the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: ${{ steps.get_repo.outputs.name }}
          # File, directory, or wildcard pattern used to find files
          path: "src/bin/Release/**/${{ steps.get_repo.outputs.name }}.dll"
