name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out source
        uses: actions/checkout@v2
      # Run common actions
      - name: Run common actions
        id: common
        uses: OxideMod/Actions@v1
      # Uploads the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: ${{ steps.common.outputs.repo-name }}
          # File, directory, or wildcard pattern used to find files
          path: "src/bin/${{ steps.common.outputs.configuration }}/**/${{ steps.common.outputs.repo-name }}.dll"
